#include <benchmark/benchmark.h>
#include <cstdio>
#include <random>
#include <vector>
#include <cassert>

uint32_t count_digits(uint32_t v) {
    uint32_t result = 0;
    do {
        ++result;
        v /= 10;
    } while (v);
    result;
}

uint32_t count_digits2(uint32_t v) {
    uint32_t result = 1;
    for (;;) {
        if (v<10)    { return result;   }
        if (v<100)   { return result+1; }
        if (v<1000)  { return result+2; }
        if (v<10000) { return result+3; }
        v /= 10000U;
        result += 4;
    }
    assert(0);
}

std::random_device seed;
std::mt19937 gen(seed());
std::vector<uint32_t> nums;

void f_benchmark(benchmark::State& state) {
  //while (state.KeepRunning()) {
    //benchmark::DoNotOptimize(f(&x[state.range(0)*64], &y[state.range(0)*64]));
    printf("%ld\n", state.range(0) );
  //  benchmark::DoNotOptimize( 
		    count_digits(state.range(0));
//		    );
  //}
}

void args(benchmark::internal::Benchmark* b) {
  const auto count = 9;
  nums.reserve(count);
  
  auto prev = 1U;
  for (int i = 0; i < count; i++) {
    auto next = prev * 10U;
    assert( (prev <= next-1) && (0 <=prev) );
    std::uniform_int_distribution<> dis(prev, next-1);
    printf("%s %d prev=%u next=%u\n", __FILE__, __LINE__, prev, next);
    uint32_t rez = dis(gen);
    printf("%u\n", rez);
    nums.push_back(rez);
    prev *= 10U;
  }
  for (int i = 0; i < count; ++i)
    b->Arg({ nums.at(i) });
}
BENCHMARK(f_benchmark)->Apply(args);
BENCHMARK_MAIN();


/*
#include <random>
#include <iostream>

int main()
{
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> dis(1, 6);

    for (int n=0; n<10; ++n)
        //Use dis to transform the random unsigned int generated by gen into an int in [1, 6]
        std::cout << dis(gen) << ' ';
    std::cout << '\n';
}
*/
